server:
  servlet:
    context-path: /api
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/shop
    username: root
    password: Oanaaaa02.
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true